zuul:
  routes:
    api:
      path: /api/**
      serviceId: api
    client:
      path: /
      serviceId: client

ribbon:
  eureka:
    enabled: false

api:
  ribbon:
    listOfServers: localhost:8081

client:
  ribbon:
    listOfServers: localhost:4200