zuul:
  routes:
    login:
      sensitiveHeaders:
      path: /api/mythaistar/login/**
      serviceId: login
    api:
      sensitiveHeaders:
      path: /api/**
      serviceId: api
    client:
      sensitiveHeaders:
      path: /**
      serviceId: client
      stripPrefix: false

ribbon:
  ReadTimeout: 60000
  eureka:
    enabled: false

api:
  ribbon:
    listOfServers: localhost:8081

client:
  ribbon:
    listOfServers: localhost:4200

login:
  ribbon:
    listOfServers: localhost:8090